Repository kcp-dev/helm-charts, pull requests merged in 2023-07, with the labels that each got.

#40 Standardize resource configuration
  charts/kcp/templates/etcd.yaml
  charts/kcp/templates/kcp-front-proxy.yaml
  charts/kcp/templates/kcp.yaml
  charts/kcp/values.yaml
Labels: approved, lgtm, size/M, dco-signoff: yes

#38 Change issuers & alliasing
  charts/kcp/templates/certmanagerissuer.yaml
  charts/kcp/templates/kcp-front-proxy.yaml
  charts/kcp/templates/kcp.yaml
  charts/kcp/templates/lets-encrypt-ca.yaml
  charts/kcp/values.yaml
Labels: approved, lgtm, size/L, dco-signoff: yes

#42 Add chart metadata to Chart.yaml
  charts/kcp/Chart.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes

#41 Add securityContexts to confine kcp pods and set fsGroup correctly
  charts/kcp/templates/kcp-front-proxy.yaml
  charts/kcp/templates/kcp.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#43 set HTTPS backend annotation on Ingress resource by default
  charts/kcp/values.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#45 add configuration options to `kcp-front-proxy` Service to expose it directly
  charts/kcp/templates/kcp-front-proxy.yaml
  charts/kcp/templates/kcp.yaml
  charts/kcp/values.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes

#46 🐛 wrap EXTERNAL_PORT to make sure it's seen as string
  charts/kcp/templates/kcp.yaml
  charts/kcp/values.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes
