Repository kcp-dev/helm-charts, pull requests merged in 2023-08, with the labels that each got.

#48 change port in external-logical-cluster-admin kubeconfig when exposing front proxy directly
  charts/kcp/templates/external-logical-cluster-admin-kubeconfig.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#49 Stop using low host port numbers; improve kind-setup doc
  README.md
  hack/generate-admin-kubeconfig.sh
  hack/kind-setup.sh
  hack/kind/config.yaml
Labels: approved, lgtm, size/M, dco-signoff: yes

#51 Enable use of embedded etcd
  charts/kcp/templates/kcp.yaml
  hack/kind-values.yaml
  hack/kind/config.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes
