Repository kcp-dev/helm-charts, pull requests merged in 2023-10, with the labels that each got.

#57 Improve kind scripting
  hack/generate-admin-kubeconfig.sh
  hack/kind-setup.sh
  hack/kind-values.yaml
  hack/kind/config.yaml
Labels: approved, lgtm, size/L, dco-signoff: yes

#66 Bump version
  charts/kcp/Chart.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#67 ⚠️ Fix components not actually using the correct CAs / Extend CA Lifetime
  README.md
  charts/kcp/templates/etcd-ca.yaml
  charts/kcp/templates/etcd-certificates.yaml
  charts/kcp/templates/etcd-issuers.yaml
  charts/kcp/templates/etcd-statefulset.yaml
  charts/kcp/templates/front-proxy-ca.yaml
  charts/kcp/templates/front-proxy-certificates.yaml
  charts/kcp/templates/front-proxy-configmap.yaml
  charts/kcp/templates/front-proxy-deployment.yaml
  charts/kcp/templates/front-proxy-ingress.yaml
  charts/kcp/templates/front-proxy-kubeconfig.yaml
  charts/kcp/templates/letsencrypt-clusterissuers.yaml
  charts/kcp/templates/pki-issuers.yaml
  charts/kcp/templates/rolebinding-edit-access.yaml
  charts/kcp/templates/server-ca.yaml
  charts/kcp/templates/server-certificates.yaml
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/templates/server-issuers.yaml
  charts/kcp/templates/server-kubeconfigs.yaml
  charts/kcp/values.yaml
  docs/pki.png
Labels: approved, size/XXL, lgtm, dco-signoff: yes

#68 🌱 Prepare 0.4.0 chart release, use appVersion to determine image tag by default
  .prow.yaml
  charts/kcp/Chart.yaml
  charts/kcp/templates/_helpers.tpl
  charts/kcp/templates/front-proxy-deployment.yaml
  charts/kcp/templates/rolebinding-edit-access.yaml
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/values.yaml
Labels: approved, lgtm, size/M, dco-signoff: yes
