Repository kcp-dev/helm-charts, pull requests merged in 2023-09, with the labels that each got.

#53 Add well-known `app.kubernetes.io` labels to all resources
  charts/kcp/templates/_helpers.tpl
  charts/kcp/templates/certmanagerissuer.yaml
  charts/kcp/templates/etcd.yaml
  charts/kcp/templates/external-logical-cluster-admin-kubeconfig.yaml
  charts/kcp/templates/front-proxy-kubeconfig.yaml
  charts/kcp/templates/issuer.yaml
  charts/kcp/templates/kcp-front-proxy.yaml
  charts/kcp/templates/kcp.yaml
  charts/kcp/templates/lets-encrypt-ca.yaml
  charts/kcp/templates/logical-cluster-admin-kubeconfig.yaml
  charts/kcp/templates/rolebinding-edit-access.yaml
Labels: approved, lgtm, size/L, dco-signoff: yes

#54 Move security context to `values.yaml`
  charts/kcp/templates/kcp-front-proxy.yaml
  charts/kcp/templates/kcp.yaml
  charts/kcp/values.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes

#56 Cleanup PKI usage, make path mapping configurable
  README.md
  charts/kcp/Chart.yaml
  charts/kcp/templates/certmanagerissuer.yaml
  charts/kcp/templates/etcd.yaml
  charts/kcp/templates/external-logical-cluster-admin-kubeconfig.yaml
  charts/kcp/templates/front-proxy-kubeconfig.yaml
  charts/kcp/templates/issuer.yaml
  charts/kcp/templates/kcp-front-proxy.yaml
  charts/kcp/templates/kcp.yaml
  charts/kcp/templates/lets-encrypt-ca.yaml
  charts/kcp/templates/logical-cluster-admin-kubeconfig.yaml
  charts/kcp/templates/rolebinding-edit-access.yaml
  charts/kcp/values.yaml
  docs/pki.png
Labels: approved, lgtm, size/L, dco-signoff: yes

#58 Add presubmit job to prevent chart from going bad
  .prow.yaml
  charts/kcp/templates/rolebinding-edit-access.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes

#59 Update service selector for etcd headless service
  charts/kcp/templates/etcd.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#60 Use kcp-client-issuer for external-admin-kubeconfig certificate
  charts/kcp/templates/kcp.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#62 Move resources into dedicated files with component prefixes
  charts/kcp/templates/etcd-ca.yaml
  charts/kcp/templates/etcd-certificates.yaml
  charts/kcp/templates/etcd-issuers.yaml
  charts/kcp/templates/etcd-statefulset.yaml
  charts/kcp/templates/front-proxy-ca.yaml
  charts/kcp/templates/front-proxy-certificates.yaml
  charts/kcp/templates/front-proxy-configmap.yaml
  charts/kcp/templates/front-proxy-deployment.yaml
  charts/kcp/templates/front-proxy-ingress.yaml
  charts/kcp/templates/front-proxy-issuers.yaml
  charts/kcp/templates/letsencrypt-clusterissuers.yaml
  charts/kcp/templates/pki-issuers.yaml
  charts/kcp/templates/server-ca.yaml
  charts/kcp/templates/server-certificates.yaml
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/templates/server-issuers.yaml
Labels: approved, size/XXL, lgtm, dco-signoff: yes

#64 Fix bug in front-proxy-certificates.yaml
  charts/kcp/templates/front-proxy-certificates.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#65 :warning: Use templated names for all resources, rework values
  charts/kcp/templates/_helpers.tpl
  charts/kcp/templates/etcd-ca.yaml
  charts/kcp/templates/etcd-certificates.yaml
  charts/kcp/templates/etcd-issuers.yaml
  charts/kcp/templates/etcd-statefulset.yaml
  charts/kcp/templates/external-logical-cluster-admin-kubeconfig.yaml
  charts/kcp/templates/front-proxy-ca.yaml
  charts/kcp/templates/front-proxy-certificates.yaml
  charts/kcp/templates/front-proxy-configmap.yaml
  charts/kcp/templates/front-proxy-deployment.yaml
  charts/kcp/templates/front-proxy-ingress.yaml
  charts/kcp/templates/front-proxy-issuers.yaml
  charts/kcp/templates/front-proxy-kubeconfig.yaml
  charts/kcp/templates/letsencrypt-clusterissuers.yaml
  charts/kcp/templates/logical-cluster-admin-kubeconfig.yaml
  charts/kcp/templates/pki-issuers.yaml
  charts/kcp/templates/server-ca.yaml
  charts/kcp/templates/server-certificates.yaml
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/templates/server-issuers.yaml
  charts/kcp/templates/server-kubeconfigs.yaml
  charts/kcp/values.yaml
Labels: approved, size/XL, lgtm, dco-signoff: yes
