Repository kcp-dev/helm-charts, pull requests merged in 2024-09, with the labels that each got.

#102 Use appropriate CA cert to reach the front-proxy
  charts/kcp/templates/front-proxy-servicemonitor.yaml
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/templates/server-kubeconfigs.yaml
  charts/kcp/values.yaml
Labels: approved, ok-to-test, lgtm, size/S, dco-signoff: yes

#104 Allow setting affinity
  charts/kcp/templates/etcd-statefulset.yaml
  charts/kcp/templates/front-proxy-deployment.yaml
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/values.yaml
Labels: approved, ok-to-test, lgtm, size/M, dco-signoff: yes

#101 Add X-Remote-Extra- headers prefix configuration
  charts/kcp/Chart.yaml
  charts/kcp/templates/server-deployment.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#99 Remove support for embedded etcd in Chart
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/values.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#107 bump kcp chart to 0.8.2
  charts/kcp/Chart.yaml
Labels: approved, size/XS, needs-ok-to-test, lgtm, dco-signoff: yes
