Repository kcp-dev/helm-charts, pull requests merged in 2024-08, with the labels that each got.

#93 Update `pull-helm-charts-render` presubmit to `build:1.22.5-1` image
  .prow.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#95 Don't make use of /bin/sh in etcd images & update etcd version
  charts/kcp/templates/etcd-statefulset.yaml
  charts/kcp/values.yaml
  charts/shard/templates/etcd-statefulset.yaml
Labels: approved, needs-ok-to-test, lgtm, size/L, dco-signoff: yes

#98 Allow for specifying storageClassName for etcd PVC
  charts/kcp/templates/etcd-statefulset.yaml
  charts/kcp/values.yaml
Labels: approved, size/XS, ok-to-test, lgtm, dco-signoff: yes

#97 fix front-proxy Ingress' backend service
  charts/kcp/templates/front-proxy-ingress.yaml
Labels: approved, size/XS, ok-to-test, lgtm, dco-signoff: yes

#96 kcp: update to kcp release 0.25.0
  charts/kcp/Chart.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes
