Repository kcp-dev/helm-charts, pull requests merged in 2024-10, with the labels that each got.

#106 front-proxy Ingress: add ingressClassName field
  charts/kcp/templates/front-proxy-ingress.yaml
  charts/kcp/values.yaml
Labels: approved, size/XS, ok-to-test, lgtm, dco-signoff: yes

#108 Make etcd service more Istio-friendly
  charts/kcp/templates/etcd-certificates.yaml
  charts/kcp/templates/etcd-statefulset.yaml
  charts/kcp/values.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes

#109 Bump kcp chart to version 0.8.3
  charts/kcp/Chart.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#110 Update appVersion to 0.26.0, Helm chart version to 0.9.0
  charts/kcp/Chart.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#112 server: wire kcp-ca as root-ca, ending up in service account token secrets
  charts/kcp/templates/server-deployment.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#111 Remove emptyDir from kcp Deployment, make root filesystem read-only
  charts/kcp/Chart.yaml
  charts/kcp/templates/server-deployment.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes

#114 fix (secret): kcp-token-auth-file
  charts/kcp/templates/front-proxy-deployment.yaml
Labels: approved, size/XS, ok-to-test, lgtm, dco-signoff: yes
