Repository kcp-dev/helm-charts, pull requests merged in 2025-06, with the labels that each got.

#144 Make LB IP configurable for kcp-front-proxy service
  charts/kcp/templates/front-proxy-deployment.yaml
  charts/kcp/values.yaml
Labels: approved, size/XS, ok-to-test, lgtm, dco-signoff: yes

#147 charts/kcp-operator: bump to initial release version v0.1.0
  charts/kcp-operator/Chart.yaml
  charts/kcp-operator/README.md
Labels: approved, lgtm, size/S, dco-signoff: yes

#150 update api-syncagent Chart for agent 0.3
  charts/api-syncagent/Chart.yaml
  charts/api-syncagent/templates/crd-publishedresource.yaml
  charts/api-syncagent/templates/deployment.yaml
  charts/api-syncagent/values.yaml
Labels: approved, lgtm, size/L, dco-signoff: yes

#151 Add kcp-operator to repository README and extend Chart README
  README.md
  charts/kcp-operator/README.md
Labels: approved, lgtm, size/M, dco-signoff: yes
