Repository kcp-dev/helm-charts, pull requests merged in 2025-01, with the labels that each got.

#118 Add authz webhook options
  charts/kcp/README.md
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/values.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes

#117 update helm readme.md docs
  README.md
Labels: approved, ok-to-test, lgtm, size/M, dco-signoff: yes

#121 add basic chart for the new api-syncagent
  charts/api-syncagent/Chart.yaml
  charts/api-syncagent/LICENSE
  charts/api-syncagent/README.md
  charts/api-syncagent/templates/_helpers.tpl
  charts/api-syncagent/templates/deployment.yaml
  charts/api-syncagent/templates/rbac.yaml
  charts/api-syncagent/values.yaml
  hack/ci/render-helm-charts.sh
Labels: approved, lgtm, size/L, dco-signoff: yes

#122 Include PublishedResource CRD in api-syncagent Helm Chart
  charts/api-syncagent/templates/crd-publishedresource.yaml
  charts/api-syncagent/values.yaml
  hack/ci/render-helm-charts.sh
Labels: approved, lgtm, size/L, dco-signoff: yes

#123 fix: lint Helm guide paragraph
  README.md
Labels: approved, size/XS, needs-ok-to-test, lgtm, dco-signoff: yes

#127 Update to api-syncagent 0.1.0 and bump chart
  charts/api-syncagent/Chart.yaml
  charts/api-syncagent/templates/_helpers.tpl
  charts/api-syncagent/templates/deployment.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes

#126 Add basic Helm chart for kcp-operator
  charts/kcp-operator/.helmignore
  charts/kcp-operator/Chart.yaml
  charts/kcp-operator/LICENSE
  charts/kcp-operator/templates/NOTES.txt
  charts/kcp-operator/templates/_helpers.tpl
  charts/kcp-operator/templates/crds.yaml
  charts/kcp-operator/templates/deployment.yaml
  charts/kcp-operator/templates/rbac.yaml
  charts/kcp-operator/templates/service.yaml
  charts/kcp-operator/templates/serviceaccount.yaml
  charts/kcp-operator/values.yaml
Labels: approved, size/XXL, lgtm, dco-signoff: yes
