Repository kcp-dev/helm-charts, pull requests merged in 2025-04, with the labels that each got.

#131 Update kcp chart to version 0.10.0 (appVersion 0.27.1)
  charts/kcp/Chart.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#137 Add Tolerations for kcp, frontProxy and etcd
  charts/kcp/templates/etcd-statefulset.yaml
  charts/kcp/templates/front-proxy-deployment.yaml
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/values.yaml
Labels: approved, ok-to-test, lgtm, size/M, dco-signoff: yes

#138 Add comments to the oidc configuration values
  charts/kcp/values.yaml
Labels: approved, size/XS, ok-to-test, lgtm, dco-signoff: yes
