Repository kcp-dev/helm-charts, pull requests merged in 2025-07, with the labels that each got.

#155 kcp: require TLS passthrough for Ingress and improve README
  charts/kcp/Chart.yaml
  charts/kcp/README.md
  charts/kcp/templates/front-proxy-certificates.yaml
  charts/kcp/templates/letsencrypt-clusterissuers.yaml
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/values.yaml
Labels: approved, lgtm, size/L, dco-signoff: yes

#156 Fix permissions agent event
  charts/api-syncagent/Chart.yaml
  charts/api-syncagent/templates/rbac.yaml
Labels: approved, lgtm, size/M, dco-signoff: yes

#157 Remove Go runtime environment vars that pin resources to requests
  charts/kcp/Chart.yaml
  charts/kcp/templates/server-deployment.yaml
Labels: approved, lgtm, size/S, dco-signoff: yes

#158 kcp: update to kcp 0.28.0
  charts/kcp/Chart.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes

#159 Enable leader election by default and configure RollingUpdate
  charts/kcp/templates/server-deployment.yaml
  charts/kcp/values.yaml
Labels: approved, size/XS, lgtm, dco-signoff: yes
